### ISSUE TITLE
Trailing zeros vs hprec parameter

### ISSUE THREAD

**Issue by zjeff222** [KenKundert/engfmt#1]
Feature request

In respect to the significant figures concept, trailing zeros should be added according to the hprec parameter even for round numbers

>>>set_preferences(hprec=3)
>>>x= Quantity(1000,'m')
>>>print(x)

1km

this result should be 1.000km to respect significant figures.  So a way to (optionnaly) get this behavior would be nice

**Comment by KenKundert** [comment]
I'm sorry, engfmt has been deprecated. All development has moved to [Quantiphy](https://quantiphy.readthedocs.io). Quantiphy provides the _strip_zeros_ preference that can be set to False, which would result in the zeros being retained as you desire.
